<?php
declare(strict_types=1);
require_once __DIR__.'/_bootstrap.php';
require_once __DIR__.'/../../includes/RateLimiter.php';
require_once __DIR__.'/../../includes/DeviceManager.php';
function ae(string $k,string $d=''):string{$v=$_ENV[$k]??$_SERVER[$k]??getenv($k);return($v===false||$v===null||$v==='')?$d:trim((string)$v);}
function aj(array $x,int $s=200):never{http_response_code($s);echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function cut(string $s,int $n):string{return function_exists('mb_substr')?mb_substr($s,0,$n,'UTF-8'):substr($s,0,$n);}
function js($v,int $n):string{$s=json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);return is_string($s)?substr($s,0,$n):'{}';}
function postj(string $u,array $h,array $p,int $t=15):array{$b=json_encode($p,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$h=array_merge(['Content-Type: application/json','Accept: application/json','User-Agent: HerculePOS-Agent/1.0'],$h);$c=curl_init($u);curl_setopt_array($c,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>4,CURLOPT_TIMEOUT=>$t,CURLOPT_HTTPHEADER=>$h,CURLOPT_POSTFIELDS=>$b]);$r=curl_exec($c);$e=curl_error($c);$s=(int)curl_getinfo($c,CURLINFO_RESPONSE_CODE);curl_close($c);$j=is_string($r)?json_decode($r,true):null;return['s'=>$s,'j'=>is_array($j)?$j:null,'e'=>$e];}
function clean(string $s):?array{$s=trim(preg_replace('/^```(?:json)?\s*|\s*```$/i','',$s)??$s);$a=strpos($s,'{');$b=strrpos($s,'}');if($a!==false&&$b!==false)$s=substr($s,$a,$b-$a+1);$j=json_decode($s,true);return is_array($j)?$j:null;}
function callp(string $p,string $prompt,int $max):array{
 if($p==='gemini'){$k=ae('GEMINI_API_KEY');if(!$k)return['skip'=>1];$m=ae('GEMINI_MODEL','gemini-2.5-flash-lite');$r=postj(rtrim(ae('GEMINI_API_BASE','https://generativelanguage.googleapis.com/v1beta'),'/').'/models/'.rawurlencode($m).':generateContent',['x-goog-api-key: '.$k],['contents'=>[['role'=>'user','parts'=>[['text'=>$prompt]]]],'generationConfig'=>['temperature'=>.15,'maxOutputTokens'=>$max,'responseMimeType'=>'application/json']]);return['s'=>$r['s'],'t'=>(string)($r['j']['candidates'][0]['content']['parts'][0]['text']??''),'e'=>$r['e']?:(string)($r['j']['error']['message']??'')];}
 if($p==='groq'){$k=ae('GROQ_API_KEY');if(!$k)return['skip'=>1];$m=ae('GROQ_MODEL','openai/gpt-oss-20b');$r=postj(rtrim(ae('GROQ_API_BASE','https://api.groq.com/openai/v1'),'/').'/chat/completions',['Authorization: Bearer '.$k],['model'=>$m,'messages'=>[['role'=>'system','content'=>'Return strict JSON only.'],['role'=>'user','content'=>$prompt]],'temperature'=>.15,'max_completion_tokens'=>$max,'response_format'=>['type'=>'json_object']]);return['s'=>$r['s'],'t'=>(string)($r['j']['choices'][0]['message']['content']??''),'e'=>$r['e']?:(string)($r['j']['error']['message']??'')];}
 if($p==='cloudflare'){$k=ae('CLOUDFLARE_AI_TOKEN');$id=ae('CLOUDFLARE_ACCOUNT_ID');if(!$k||!$id)return['skip'=>1];$m=ae('CLOUDFLARE_AI_MODEL','@cf/meta/llama-3.1-8b-instruct-fast');$u=rtrim(ae('CLOUDFLARE_API_BASE','https://api.cloudflare.com/client/v4'),'/').'/accounts/'.rawurlencode($id).'/ai/run/'.str_replace('%2F','/',rawurlencode($m));$r=postj($u,['Authorization: Bearer '.$k],['prompt'=>$prompt,'max_tokens'=>$max,'temperature'=>.15]);return['s'=>$r['s'],'t'=>(string)($r['j']['result']['response']??''),'e'=>$r['e']?:(string)($r['j']['errors'][0]['message']??'')];}
 return['skip'=>1];}
function providers(string $prompt,int $max):array{$errs=[];foreach(array_filter(array_map('trim',explode(',',strtolower(ae('HERCULE_AI_PROVIDER_ORDER','gemini,groq,cloudflare')))))as$p){$r=callp($p,$prompt,$max);if(!empty($r['skip'])){$errs[]="$p:not_configured";continue;}$j=clean((string)($r['t']??''));if($j)return['ok'=>1,'provider'=>$p,'json'=>$j];$errs[]=$p.':'.($r['s']??0).':'.substr((string)($r['e']??'invalid_json'),0,100);}return['ok'=>0,'errors'=>$errs];}
if(($_SERVER['REQUEST_METHOD']??'')!=='POST')aj(['ok'=>false,'code'=>'METHOD_NOT_ALLOWED'],405);$b=json_input();$lk=trim((string)($b['license_key']??''));$hw=trim((string)($b['hwid']??''));$q=trim((string)($b['question']??''));$mode=strtolower(trim((string)($b['mode']??'plan')));if(!$lk||!$hw)aj(['ok'=>false,'code'=>'LICENSE_REQUIRED'],401);if(!$q||strlen($q)>6000)aj(['ok'=>false,'code'=>'INVALID_QUESTION'],400);if(DeviceManager::isBlocked($lk,$hw))aj(['ok'=>false,'code'=>'DEVICE_BLOCKED'],403);$v=License::validate($lk,$hw,client_ip());if(!($v['ok']??false))aj(['ok'=>false,'code'=>'LICENSE_INVALID'],403);$pl=max(1,(int)ae('HERCULE_AI_PER_LICENSE_RPM','12'));$gl=max($pl,(int)ae('HERCULE_AI_GLOBAL_RPM','30'));$buck='lic:'.substr(hash('sha256',$lk),0,40);if(!RateLimiter::check($buck,'ai_agent_'.$mode,$pl,1)||!RateLimiter::check('global','ai_agent_global_'.$mode,$gl,1))aj(['ok'=>false,'code'=>'AI_RATE_LIMIT','error'=>'التحليل الذكي مشغول حالياً.'],429);
$cat=json_decode((string)@file_get_contents(__DIR__.'/intent_catalog.json'),true);if(!is_array($cat))aj(['ok'=>false,'code'=>'CATALOG_ERROR'],500);$ctx=is_array($b['context']??null)?$b['context']:[];
if($mode==='plan'){$names=[];foreach($cat as$n=>$m)if($n!=='none')$names[]=$n.(!empty($m['entity'])?'['.$m['entity'].']':'');$prompt="You are the planning brain for Hercule POS. User can write Iraqi Arabic, Arabic or English. Never invent store data. Store facts must come from local read-only tools. You may answer general knowledge/chat directly. For Hercule usage/settings use help_search. For analysis request several reports when useful. For prediction use forecast tools, never guess numbers. Allowed tools: report{intent,entity_type,entity_query,limit,window_days}; forecast_sales{horizon_days,history_days}; forecast_inventory{horizon_days,lookback_days,limit}; forecast_product{entity_query,horizon_days,lookback_days}; help_search{query,limit}. Report intents: ".implode(',',$names).". Context: ".js($ctx,14000)." Question: $q Return JSON only: either {\"kind\":\"answer\",\"answer\":{\"answer\":\"...\",\"key_points\":[],\"recommendations\":[],\"confidence\":\"high|medium|low\",\"followups\":[],\"navigation\":[]},\"tool_calls\":[]} or {\"kind\":\"tools\",\"goal\":\"...\",\"tool_calls\":[...max 8...]}.";$r=providers($prompt,900);if(!$r['ok'])aj(['ok'=>false,'code'=>'AI_PROVIDERS_UNAVAILABLE','providers'=>$r['errors']],503);$x=$r['json'];$calls=[];foreach(array_slice(is_array($x['tool_calls']??null)?$x['tool_calls']:[],0,8)as$c){if(!is_array($c))continue;$t=strtolower(trim((string)($c['tool']??'')));if(!in_array($t,['report','forecast_sales','forecast_inventory','forecast_product','help_search'],true))continue;if($t==='report'){if(!isset($cat[$c['intent']??''])||($c['intent']??'')==='none')continue;$req=(string)($cat[$c['intent']]['entity']??'');$et=(string)($c['entity_type']??'none');$eq=cut(trim((string)($c['entity_query']??'')),120);if($req&&($et!==$req||!$eq))continue;$calls[]=['tool'=>'report','intent'=>$c['intent'],'entity_type'=>$et,'entity_query'=>$eq,'limit'=>max(1,min(50,(int)($c['limit']??10))),'window_days'=>max(1,min(3650,(int)($c['window_days']??30)))];}elseif($t==='forecast_product'){if(!trim((string)($c['entity_query']??'')))continue;$calls[]=['tool'=>$t,'entity_query'=>cut(trim((string)$c['entity_query']),120),'horizon_days'=>max(1,min(90,(int)($c['horizon_days']??14))),'lookback_days'=>max(7,min(120,(int)($c['lookback_days']??30)))];}elseif($t==='help_search'){$calls[]=['tool'=>$t,'query'=>cut(trim((string)($c['query']??$q)),500),'limit'=>max(1,min(8,(int)($c['limit']??5)))];}else{$calls[]=['tool'=>$t,'horizon_days'=>max(1,min(90,(int)($c['horizon_days']??($t==='forecast_sales'?7:14)))),'history_days'=>max(28,min(365,(int)($c['history_days']??84))),'lookback_days'=>max(7,min(180,(int)($c['lookback_days']??30))),'limit'=>max(1,min(50,(int)($c['limit']??20)))];}}
 $plan=$calls?['kind'=>'tools','goal'=>cut((string)($x['goal']??''),300),'tool_calls'=>$calls]:['kind'=>'answer','answer'=>is_array($x['answer']??null)?$x['answer']:['answer'=>(string)($x['answer']??'')],'tool_calls'=>[]];aj(['ok'=>true,'provider'=>$r['provider'],'plan'=>$plan]);}
if($mode!=='synthesize')aj(['ok'=>false,'code'=>'INVALID_MODE'],400);$plan=is_array($b['plan']??null)?$b['plan']:[];$tools=is_array($b['tool_results']??null)?array_slice($b['tool_results'],0,8):[];$prompt="You are Hercule POS smart assistant. Use ONLY supplied local tool results for store-specific facts. Never invent numbers or causes. Forecasts are probabilistic: mention confidence/range and never guarantee. App-help must follow supplied help steps/settings. Answer in user's language, Iraqi Arabic for Iraqi Arabic. Return JSON only: {\"answer\":\"...\",\"key_points\":[],\"recommendations\":[],\"confidence\":\"high|medium|low\",\"followups\":[],\"navigation\":[{\"view\":\"dashboard|sell|shifts|inventory|customers|expenses|reports|ask|settings|invoices|promotions|purchasing\",\"label\":\"...\"}],\"caveat\":\"\"}. Question: $q Plan: ".js($plan,5000)." Tool results: ".js($tools,24000)." Context: ".js($ctx,7000);$r=providers($prompt,1200);if(!$r['ok'])aj(['ok'=>false,'code'=>'AI_PROVIDERS_UNAVAILABLE','providers'=>$r['errors']],503);$a=$r['json'];if(!trim((string)($a['answer']??'')))aj(['ok'=>false,'code'=>'AI_INVALID_RESPONSE'],502);$a['answer']=cut((string)$a['answer'],5000);aj(['ok'=>true,'provider'=>$r['provider'],'answer'=>$a]);
