<?php

declare(strict_types=1);

final class ReleaseStorage
{
    private const DEFAULT_MAX_UPLOAD_MB = 512;
    private const MAX_MANIFEST_BYTES = 256 * 1024;
    private const MAX_BLOCKMAP_BYTES = 32 * 1024 * 1024;
    private const MAX_METADATA_BYTES = 1024 * 1024;

    public static function baseDir(): string
    {
        $configured = trim((string)($_ENV['HERCULE_RELEASE_STORAGE_DIR'] ?? $_SERVER['HERCULE_RELEASE_STORAGE_DIR'] ?? getenv('HERCULE_RELEASE_STORAGE_DIR') ?: ''));
        if ($configured !== '') {
            return rtrim($configured, DIRECTORY_SEPARATOR);
        }

        if (PHP_OS_FAMILY !== 'Windows' && is_dir('/home')) {
            return '/home/data/hercule-pos/releases';
        }

        return dirname(__DIR__) . '/storage/releases';
    }

    public static function ensureWritable(): string
    {
        $base = self::baseDir();
        if (!is_dir($base) && !@mkdir($base, 0770, true) && !is_dir($base)) {
            throw new RuntimeException('Release storage directory could not be created.');
        }
        if (!is_writable($base)) {
            throw new RuntimeException('Release storage directory is not writable.');
        }
        return $base;
    }

    public static function maxUploadBytes(): int
    {
        $raw = (int)($_ENV['HERCULE_RELEASE_MAX_UPLOAD_MB'] ?? $_SERVER['HERCULE_RELEASE_MAX_UPLOAD_MB'] ?? getenv('HERCULE_RELEASE_MAX_UPLOAD_MB') ?: self::DEFAULT_MAX_UPLOAD_MB);
        $mb = max(64, min(2048, $raw));
        return $mb * 1024 * 1024;
    }

    public static function importBundle(array $upload): array
    {
        if (!class_exists('ZipArchive')) {
            throw new RuntimeException('PHP ZipArchive extension is required for update bundle uploads.');
        }

        $error = (int)($upload['error'] ?? UPLOAD_ERR_NO_FILE);
        if ($error !== UPLOAD_ERR_OK) {
            throw new RuntimeException(self::uploadErrorMessage($error));
        }

        $tmp = (string)($upload['tmp_name'] ?? '');
        $originalName = basename((string)($upload['name'] ?? 'update.zip'));
        $size = (int)($upload['size'] ?? 0);
        if ($tmp === '' || !is_file($tmp) || $size <= 0) {
            throw new InvalidArgumentException('Uploaded update bundle is missing or empty.');
        }
        if ($size > self::maxUploadBytes()) {
            throw new InvalidArgumentException('Update bundle exceeds the configured upload size limit.');
        }
        if (strtolower(pathinfo($originalName, PATHINFO_EXTENSION)) !== 'zip') {
            throw new InvalidArgumentException('Update bundle must be a ZIP file generated by Hercule build.');
        }

        $zip = new ZipArchive();
        $open = $zip->open($tmp, ZipArchive::RDONLY);
        if ($open !== true) {
            throw new InvalidArgumentException('Update bundle ZIP could not be opened.');
        }

        $staging = null;
        try {
            if ($zip->numFiles < 4 || $zip->numFiles > 12) {
                throw new InvalidArgumentException('Update bundle has an unexpected number of files.');
            }

            $entries = [];
            for ($i = 0; $i < $zip->numFiles; $i++) {
                $name = (string)$zip->getNameIndex($i);
                if ($name === '' || str_ends_with($name, '/') || basename($name) !== $name || str_contains($name, '..') || str_contains($name, '\\')) {
                    throw new InvalidArgumentException('Update bundle contains an unsafe path.');
                }
                if (isset($entries[$name])) {
                    throw new InvalidArgumentException('Update bundle contains duplicate file names.');
                }
                $entries[$name] = true;
            }

            if (!isset($entries['manifest.json'])) {
                throw new InvalidArgumentException('manifest.json is missing from the update bundle.');
            }

            // Inspect the ZIP directory before decompression. getFromName()
            // would otherwise inflate the entire manifest before the length
            // check, allowing a tiny compressed ZIP entry to consume excessive
            // memory. statIndex + bounded getFromIndex keeps this fail-closed.
            $manifestIndex = $zip->locateName('manifest.json');
            $manifestStat = $manifestIndex !== false ? $zip->statIndex($manifestIndex) : false;
            $manifestSize = is_array($manifestStat) ? (int)($manifestStat['size'] ?? -1) : -1;
            if ($manifestIndex === false || $manifestSize < 2 || $manifestSize > self::MAX_MANIFEST_BYTES) {
                throw new InvalidArgumentException('manifest.json is invalid or exceeds the safety limit.');
            }
            $manifestText = $zip->getFromIndex($manifestIndex, self::MAX_MANIFEST_BYTES + 1);
            if (!is_string($manifestText) || strlen($manifestText) !== $manifestSize) {
                throw new InvalidArgumentException('manifest.json is invalid.');
            }
            $manifest = json_decode($manifestText, true);
            if (!is_array($manifest)) {
                throw new InvalidArgumentException('manifest.json is not valid JSON.');
            }

            self::validateManifest($manifest, $entries);
            $version = (string)$manifest['version'];
            $safeVersion = preg_replace('/[^0-9A-Za-z._+-]/', '_', $version) ?: 'unknown';
            $base = self::ensureWritable();
            $finalKey = 'v' . $safeVersion;
            $finalDir = $base . DIRECTORY_SEPARATOR . $finalKey;
            if (file_exists($finalDir)) {
                throw new InvalidArgumentException('A stored update bundle already exists for version ' . $version . '.');
            }

            $staging = $base . DIRECTORY_SEPARATOR . '.staging-' . bin2hex(random_bytes(8));
            if (!mkdir($staging, 0770, true)) {
                throw new RuntimeException('Could not create release staging directory.');
            }

            $files = [
                'installer' => $manifest['installer'],
                'blockmap' => $manifest['blockmap'],
                'metadata' => $manifest['updater_metadata'],
            ];

            foreach ($files as $kind => $meta) {
                $name = (string)$meta['file'];
                $dest = $staging . DIRECTORY_SEPARATOR . $name;
                self::extractEntry($zip, $name, $dest, (int)$meta['size']);
                self::verifyArtifact($dest, $meta, $kind === 'installer');
            }

            $bundleName = 'hercule-pos-update-' . $safeVersion . '.zip';
            $bundleDest = $staging . DIRECTORY_SEPARATOR . $bundleName;
            if (!@copy($tmp, $bundleDest)) {
                throw new RuntimeException('Could not archive the uploaded update bundle.');
            }
            $bundleSha256 = hash_file('sha256', $bundleDest);
            if (!is_string($bundleSha256) || strlen($bundleSha256) !== 64) {
                throw new RuntimeException('Could not calculate update bundle SHA-256.');
            }

            $storedManifest = json_encode($manifest, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
            if (!is_string($storedManifest)
                || file_put_contents($staging . DIRECTORY_SEPARATOR . 'manifest.json', $storedManifest . "\n", LOCK_EX) === false) {
                throw new RuntimeException('Could not store verified update manifest.');
            }

            if (!@rename($staging, $finalDir)) {
                throw new RuntimeException('Could not finalize release storage directory.');
            }
            $staging = null;

            return [
                'manifest' => $manifest,
                'storage_key' => $finalKey,
                'bundle_filename' => $bundleName,
                'bundle_size' => filesize($finalDir . DIRECTORY_SEPARATOR . $bundleName) ?: $size,
                'bundle_sha256' => $bundleSha256,
            ];
        } finally {
            $zip->close();
            if ($staging !== null && is_dir($staging)) {
                self::removeTree($staging);
            }
        }
    }

    public static function artifactPath(array $release, string $artifact): array
    {
        $columnMap = [
            'installer' => ['installer_filename', 'application/octet-stream'],
            'blockmap' => ['blockmap_filename', 'application/octet-stream'],
            'metadata' => ['metadata_filename', 'text/yaml; charset=utf-8'],
            'bundle' => ['bundle_filename', 'application/zip'],
        ];
        if (!isset($columnMap[$artifact])) {
            throw new InvalidArgumentException('Unknown release artifact.');
        }

        [$column, $mime] = $columnMap[$artifact];
        $storageKey = basename((string)($release['storage_key'] ?? ''));
        $file = basename((string)($release[$column] ?? ''));
        if ($storageKey === '' || $file === '') {
            throw new RuntimeException('Release artifact metadata is incomplete.');
        }

        $base = realpath(self::ensureWritable());
        $dir = realpath(self::baseDir() . DIRECTORY_SEPARATOR . $storageKey);
        $path = $dir ? realpath($dir . DIRECTORY_SEPARATOR . $file) : false;
        if (!$base || !$dir || !$path || !str_starts_with($dir, $base . DIRECTORY_SEPARATOR) || !str_starts_with($path, $dir . DIRECTORY_SEPARATOR) || !is_file($path)) {
            throw new RuntimeException('Release artifact file is unavailable.');
        }

        return ['path' => $path, 'filename' => $file, 'mime' => $mime, 'size' => filesize($path) ?: 0];
    }

    public static function deleteReleaseFiles(?string $storageKey): void
    {
        $storageKey = basename(trim((string)$storageKey));
        if ($storageKey === '') return;
        $base = self::ensureWritable();
        $dir = $base . DIRECTORY_SEPARATOR . $storageKey;
        if (is_dir($dir)) self::removeTree($dir);
    }

    private static function validateManifest(array $m, array $entries): void
    {
        if ((int)($m['schema_version'] ?? 0) !== 1 || ($m['bundle_type'] ?? '') !== 'hercule-pos-update') {
            throw new InvalidArgumentException('Update bundle manifest schema is not supported.');
        }
        $version = trim((string)($m['version'] ?? ''));
        if (!preg_match('/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/', $version)) {
            throw new InvalidArgumentException('Update bundle version is invalid.');
        }
        if (($m['platform'] ?? '') !== 'win32' || ($m['arch'] ?? '') !== 'x64') {
            throw new InvalidArgumentException('Only Windows x64 Hercule update bundles are supported.');
        }
        if (($m['app_id'] ?? '') !== 'com.hercule.pos') {
            throw new InvalidArgumentException('Update bundle app identity does not match Hercule POS.');
        }

        $sizeLimits = [
            'installer' => self::maxUploadBytes(),
            'blockmap' => self::MAX_BLOCKMAP_BYTES,
            'updater_metadata' => self::MAX_METADATA_BYTES,
        ];
        foreach (['installer', 'blockmap', 'updater_metadata'] as $key) {
            $meta = $m[$key] ?? null;
            if (!is_array($meta)) throw new InvalidArgumentException("Manifest section {$key} is missing.");
            $file = (string)($meta['file'] ?? '');
            if ($file === '' || basename($file) !== $file || !isset($entries[$file])) {
                throw new InvalidArgumentException("Manifest artifact {$key} is missing from ZIP.");
            }
            $sha = strtolower((string)($meta['sha256'] ?? ''));
            if (!preg_match('/^[a-f0-9]{64}$/', $sha)) {
                throw new InvalidArgumentException("Manifest SHA-256 for {$key} is invalid.");
            }
            $declaredSize = (int)($meta['size'] ?? 0);
            if ($declaredSize <= 0 || $declaredSize > $sizeLimits[$key]) {
                throw new InvalidArgumentException("Manifest size for {$key} is invalid or exceeds the safety limit.");
            }
        }

        if (!preg_match('/\.exe$/i', (string)$m['installer']['file']) || !preg_match('/\.blockmap$/i', (string)$m['blockmap']['file']) || strtolower((string)$m['updater_metadata']['file']) !== 'latest.yml') {
            throw new InvalidArgumentException('Update bundle artifact names are not recognized.');
        }
        $sha512 = (string)($m['installer']['sha512'] ?? '');
        $sha512Raw = base64_decode($sha512, true);
        if (!is_string($sha512Raw) || strlen($sha512Raw) !== 64) {
            throw new InvalidArgumentException('Installer SHA-512 is missing or invalid.');
        }
    }

    private static function extractEntry(ZipArchive $zip, string $name, string $dest, int $expectedSize): void
    {
        if ($expectedSize <= 0) throw new InvalidArgumentException('Update artifact size is invalid.');
        $in = $zip->getStream($name);
        if (!is_resource($in)) throw new RuntimeException('Could not read update bundle artifact ' . $name . '.');
        $out = fopen($dest, 'wb');
        if (!is_resource($out)) {
            fclose($in);
            throw new RuntimeException('Could not create stored release artifact ' . $name . '.');
        }
        try {
            // Never decompress an entry without a hard byte ceiling. Reading at
            // most expectedSize + 1 turns a malformed/compression-bomb entry
            // into a bounded validation failure instead of filling server disk.
            $copied = stream_copy_to_stream($in, $out, $expectedSize + 1);
            if ($copied === false || $copied !== $expectedSize) {
                throw new InvalidArgumentException('Update bundle artifact size does not match manifest.');
            }
            fflush($out);
        } finally {
            fclose($in);
            fclose($out);
        }
    }

    private static function verifyArtifact(string $path, array $meta, bool $checkSha512): void
    {
        $size = filesize($path);
        if ($size === false || $size !== (int)$meta['size']) {
            throw new InvalidArgumentException('Stored update artifact size does not match manifest.');
        }
        $sha256 = hash_file('sha256', $path);
        if (!hash_equals(strtolower((string)$meta['sha256']), strtolower((string)$sha256))) {
            throw new InvalidArgumentException('Stored update artifact SHA-256 does not match manifest.');
        }
        if ($checkSha512) {
            $sha512 = base64_encode(hash_file('sha512', $path, true));
            if (!hash_equals((string)$meta['sha512'], $sha512)) {
                throw new InvalidArgumentException('Installer SHA-512 does not match manifest.');
            }
        }
    }

    private static function removeTree(string $dir): void
    {
        if (!is_dir($dir)) return;
        $items = scandir($dir);
        if (!is_array($items)) return;
        foreach ($items as $item) {
            if ($item === '.' || $item === '..') continue;
            $path = $dir . DIRECTORY_SEPARATOR . $item;
            if (is_dir($path)) self::removeTree($path); else @unlink($path);
        }
        @rmdir($dir);
    }

    private static function uploadErrorMessage(int $code): string
    {
        return match ($code) {
            UPLOAD_ERR_INI_SIZE, UPLOAD_ERR_FORM_SIZE => 'Uploaded update bundle is larger than the server upload limit.',
            UPLOAD_ERR_PARTIAL => 'Update bundle upload was interrupted before completion.',
            UPLOAD_ERR_NO_FILE => 'Choose an update bundle ZIP first.',
            UPLOAD_ERR_NO_TMP_DIR => 'Server temporary upload directory is unavailable.',
            UPLOAD_ERR_CANT_WRITE => 'Server could not write the uploaded bundle.',
            UPLOAD_ERR_EXTENSION => 'A server extension stopped the upload.',
            default => 'Update bundle upload failed.',
        };
    }
}
