name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: b1a9c06a-1d54-426b-b5d9-cd2977effe08
          tenant-id: cb4f9603-299f-4515-b736-2d50c9c37494
          subscription-id: e2eb7728-917f-4818-b7d7-8e82228f9d22

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: pos
